ClientDashboard/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from ClientDashboard.views import PortfolioView, Dashboard, AppointmentScheduler, Overview, welcome
from ClientDashboard import views

urlpatterns = [

    url(r'^portfolio/$', PortfolioView.as_view(), name=u'profile'),
    url(r'^portfolio/(?P<user_id>\d+)/$', PortfolioView.as_view(), name=u'profile'),
    url(r'^$', Dashboard.as_view(), name=u'dashboard'),
    url(r'^appointment_scheduler/$', AppointmentScheduler.as_view(), name=u'appointment_scheduler'),
    url(r'^client_register$', views.client_register, name=u'client_register'),
    url(r'^logout', views.logout, name=u'logout'),
    url(r'^welcome', views.welcome, name=u'welcome'),
    url(r'^confirmation/(?P<confirmation_code>\w+)/(?P<username>\w+)$', views.confirmation),
    url(r'^client_login$', views.client_login, name=u'client_login'),
    url(r'^auth$', views.auth_view, name=u'authenticate'),
    url(r'^overview/$', views.Overview, name=u'overview'),
    url(r'^design_upload/$', views.design_upload, name=u'design_upload'),
    url(r'^project_upload/$', views.project_upload, name=u'project_upload'),
    url('load_sub_category$', views.load_sub_category, name='load_sub_category'),
    url('upload_details$', views.upload_details, name='upload_details'),
    url(r'^delete_design$', views.delete_design, name='delete_design'),
    url('load_upload_form', views.load_upload_form, name='load_upload_form'),
    url('send_sms', views.send_sms_user, name='send_sms'),
]

IUNGO/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^client/', include('ClientDashboard.urls')),
    url(r'^', include('website.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ClientDashboard/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
from datetime import date
from .validations import validate_file_extension

import datetime, os

from django.core.files.storage import FileSystemStorage

# Create your models here.

PREFIX_CHOICES = (
    ('MR', 'MR'),
    ('MRS', 'MRS'),
    ('MS', 'MS'),
    ('MX', 'MX')
)

RATING_CHOICES = [(i,i) for i in range(1,6)]

EXPERIENCE_CHOICES = [
    ('0-5', '0-5'),
    ('6-10', '6-10'),
    ('11-15', '11-15'),
    ('16-20', '16-20'),
    ('21-25', '21-25'),
    ('26-30', '26-30'),
    ('31-35', '31-35'),
    ('36-40', '36-40'),
    ('41-45', '41-45'),
    ('46-50', '46-50'),
    ('51-55', '51-55'),
    ('56-60', '56-60'),
    ('61-65', '61-65'),
    ('66-70', '66-70'),
]

BUDGET_CHOICES = (
    ('0-10', '0-10'),
    ('11-20', '11-20'),
    ('21-30', '21-30'),
    ('31-40', '31-40'),
    ('41-50', '41-50'),
    ('51-60', '51-60'),
    ('61-70', '61-70'),
    ('71-80', '71-80'),
    ('81-90', '81-90'),
    ('91-100', '91-100'),
)

QUALIFICATION_CHOICES = (
    ('UG', 'UNDER GRADUATE'),
    ('G', 'GRADUATE'),
    ('PG', 'POST GRADUATE'),
    ('PhD', 'PhD'),
)

GENDER_CHOICES = (
    ('MALE', 'MALE'),
    ('FEMALE', 'FEMALE'),
    ('OTHERS', 'OTHERS'),
)

def change_file_path(instance, filename):
    ''' This function generates a random string of length 16 which will be a combination of (4 digits + 4
    characters(lowercase) + 4 digits + 4 characters(uppercase)) seperated 4 characters by hyphen(-) '''

    import random
    import string

    # random_str length will be 16 which will be combination of (4 digits + 4 characters + 4 digits + 4 characters)

    filetype = filename.split(".")[-1].lower()
    filename = filename + "." + filetype
    path = "ClientDashboard/uploads/" + str(datetime.datetime.now().year) + "/" + str(
        datetime.datetime.now().month) + "/" + str(datetime.datetime.now().day) + "/"
    os_path = os.path.join(path, filename)
    return os_path

def content_file_name(instance, filename):
    ''' This function generates a random string of length 16 which will be a combination of (4 digits + 4
    characters(lowercase) + 4 digits + 4 characters(uppercase)) seperated 4 characters by hyphen(-) '''

    import random
    import string

    # random_str length will be 16 which will be combination of (4 digits + 4 characters + 4 digits + 4 characters)

    filetype = filename.split(".")[-1].lower()
    filename = filename
    path = "uploads/" + str(instance.user)
    os_path = os.path.join(path, filename)
    return os_path

class ConfirmationCode(models.Model):

    user = models.ForeignKey(User, default=True, on_delete=models.CASCADE)
    confirmation_code = models.CharField(verbose_name="Confirmation Code", max_length=100, blank=False, null=False,
                                         unique=True)

    def __unicode__(self):
        return u'{0}'.format(
            self.confirmation_code)

class Category(models.Model):
    name = models.CharField(verbose_name="Name", max_length=50)

    def __str__(self):
        return self.name

class sub_category(models.Model):
    name = models.CharField(verbose_name="Name", max_length=30)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class child_sub_category(models.Model):
    name = models.CharField(verbose_name="Name", max_length=30)
    sub_category = models.ForeignKey(sub_category, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Design(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    design_type = models.ForeignKey(sub_category, on_delete=models.CASCADE)
    design_name = models.CharField(verbose_name="Design project Name", max_length=30)
    design_images = models.FileField(upload_to=content_file_name, blank=True, null=True, verbose_name="Design Images")
    design_number = models.CharField(verbose_name="Design Number", max_length=10)

    def __unicode__(self):
        return u'{0}'.format(self.design_name)


class Project(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    project_type = models.ForeignKey(sub_category, on_delete=models.CASCADE)
    project_name = models.CharField(verbose_name="Project Name", max_length=30)
    project_images = models.FileField(upload_to=content_file_name, blank=True, null=True, verbose_name="Project Images")
    project_number = models.CharField(verbose_name="project Number", max_length=10)

    def __unicode__(self):
        return u'{0}'.format(self.project_name)


class Portfolio(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    experience = models.CharField(verbose_name="Experience", max_length=10, choices=EXPERIENCE_CHOICES, blank=False,
                                  null=False)
    qualification = models.CharField(verbose_name="Qualification", max_length=20, choices=QUALIFICATION_CHOICES,
                                     blank=False, null=False)
    budget = models.CharField(verbose_name="Budget", max_length=20, choices=BUDGET_CHOICES)
    prefix = models.CharField(verbose_name="Prefix", max_length=3, choices=PREFIX_CHOICES)
    gender = models.CharField(verbose_name="Gender", max_length=10, choices=GENDER_CHOICES)
    mobile_phone = models.CharField(verbose_name="Mobile phone", max_length=10, unique=True, blank=False, null=True)
    secondary_phone = models.CharField(verbose_name="Secondary phone", max_length=10, blank=False,
                                       null=True)
    date_of_birth = models.DateField(verbose_name='Date of Birth', null=True, blank=True)
    about_me = models.CharField(verbose_name="About me ", blank=True, max_length=250)
    profile_pic = models.FileField(upload_to=content_file_name, blank=True, null=True, verbose_name="Profile Picture")
    location = models.CharField(verbose_name="location", max_length=30)
    client = models.BooleanField(verbose_name="Client", default=0)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    sub_category = models.ForeignKey(sub_category, on_delete=models.CASCADE)
    child_sub_category=models.ForeignKey(child_sub_category,on_delete=models.CASCADE)

    def __str__(self):
        return self.user

@receiver(post_save, sender=User)
def create_client_profile(sender, instance, created, **kwargs):
    if created:
        category = Category.objects.get(id=1)
        subcategory = sub_category.objects.get(id=1)
        child = child_sub_category.objects.get(id=1)
        Portfolio.objects.create(user=instance, category=category, sub_category=subcategory,
                                 child_sub_category=child)

@receiver(post_save, sender=User)
def save_client_profile(sender, instance, **kwargs):
    instance.portfolio.save()


class WalkinCustomer(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    name = models.CharField(verbose_name="Name", max_length=30)
    email = models.EmailField(verbose_name="email", max_length=70, blank=True)
    mobile_phone = models.CharField(verbose_name="Mobile phone", max_length=10, unique=True, blank=False, null=True)
    date_time = models.DateField(verbose_name="Actual BRS Start Date", blank=True, null=True)

    def __str__(self):
        return self.user

class DeisgnUploads(models.Model):
    user = models.ForeignKey(User, related_name="client_designs", on_delete=models.CASCADE)
    customer = models.ForeignKey(User, related_name="customer_designs", on_delete=models.CASCADE)
    design_type = models.ForeignKey(child_sub_category, on_delete=models.CASCADE)
    design_name = models.CharField(verbose_name="Design project Name", max_length=30)
    design_images = models.FileField(upload_to=content_file_name)
    date_time = models.DateField(verbose_name="Actual BRS Start Date", blank=True, null=True)

    def __unicode__(self):
        return u'{0}'.format(self.user)

class InvoicesProposalsUploads(models.Model):
    user = models.ForeignKey(User, related_name="client_invoice_and_proposals", on_delete=models.CASCADE)
    customer = models.ForeignKey(User, related_name="customer_invoice_and_proposals", on_delete=models.CASCADE)
    invoices = models.FileField(upload_to=change_file_path, validators=[validate_file_extension], verbose_name="Invoices")
    proposals = models.FileField(upload_to=change_file_path, validators=[validate_file_extension], verbose_name="Proposals")
    date_time = models.DateField(verbose_name="Actual BRS Start Date", blank=True, null=True)

    def __unicode__(self):
        return u'{0}'.format(self.user)

# class AppointmentScheduler(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     slots_booked = models.ForeignKey(Appointment, on_delete=models.CASCADE)
#
#     def __unicode__(self):
#         return u'{0}'.format(self.user)

ClientDashboard/forms.py
import allauth.app_settings
from allauth import app_settings
from allauth.utils import get_username_max_length, set_form_field_order
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import pgettext

from .models import *
from allauth.account.forms import LoginForm, PasswordField

GENDER_CHOICES = (
    ('MALE', 'MALE'),
    ('FEMALE', 'FEMALE'),
    ('OTHERS', 'OTHERS'),
)


class MyModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return "{}".format(obj.name)


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=40)
    mobile_phone = forms.RegexField(max_length=10, required=True, regex=r'^\+?1?\d{9,15}$', widget=forms.TextInput(
        attrs={'class': 'input-sm form-control width-30', 'type': 'tel', 'pattern': '^\+?1?\d{9,15}$'}))
    password1 = forms.CharField(required=True, widget=forms.PasswordInput())
    password2 = forms.CharField(required=True, widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['email', 'mobile_phone', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['mobile_phone'].widget.attrs['class'] = \
            "form-control"
        self.fields['mobile_phone'].widget.attrs['placeholder'] = 'Mobile Number'
        self.fields['email'].widget.attrs['class'] = \
            "form-control"
        self.fields['email'].widget.attrs['placeholder'] = 'Email ID'
        self.fields['password1'].widget.attrs['class'] = \
            "form-control"
        self.fields['password1'].widget.attrs['placeholder'] = 'Password should be more than 8 letters and alphanumeric'
        self.fields['password2'].widget.attrs['class'] = \
            "form-control"
        self.fields['password2'].widget.attrs['placeholder'] = 'Password should be more than 8 letters and alphanumeric'

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Email already exists. Try a different Email-ID")
        return email
        # username = self.data['mobile_phone']
        # if User.objects.filter(username=username).exists():
        #     raise forms.ValidationError("Phone number already exists. Try a different Phone number")

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)

        user.email = self.cleaned_data['email']
        # user.username = self.cleaned_data['mobile_phone']
        if commit:
            user.save()
        return user

class DesignUploadsForm(forms.ModelForm):

    design_type = MyModelChoiceField(queryset=sub_category.objects.all())
    design_images = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

    class Meta:
        model = Design
        fields = ['design_type', 'design_name', 'design_images']
        exclude = ['user']

    def __init__(self, *args, **kwargs):
        super(DesignUploadsForm, self).__init__(*args, **kwargs)
        self.fields['design_type'].widget.attrs['class'] = \
            "form-control"
        self.fields['design_name'].widget.attrs['class'] = \
            "form-control"
        self.fields['design_images'].widget.attrs['class'] = \
            "form-control"
        self.fields['design_images'].required = False

class ProjectUploadsForm(forms.ModelForm):

    project_type = MyModelChoiceField(queryset=sub_category.objects.all())
    project_images = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

    class Meta:
        model = Project
        fields = ['project_type', 'project_name', 'project_images']
        exclude = ['user']

    def __init__(self, *args, **kwargs):
        super(ProjectUploadsForm, self).__init__(*args, **kwargs)
        self.fields['project_type'].widget.attrs['class'] = \
            "form-control"
        self.fields['project_name'].widget.attrs['class'] = \
            "form-control"
        self.fields['project_images'].widget.attrs['class'] = \
            "form-control"
        self.fields['project_images'].required = False

class PortfolioForm(forms.ModelForm):
    about_me = forms.CharField(widget=forms.Textarea(attrs={'rows': 10, 'cols': 30}))
    category = MyModelChoiceField(
        queryset=Category.objects.all(),
        required=False, )
    sub_category = MyModelChoiceField(queryset=sub_category.objects.all())

    class Meta:
        model = Portfolio
        fields = ['prefix', 'secondary_phone', 'gender',
                  'experience', 'qualification', 'profile_pic', 'about_me', 'budget', 'category',
                  'sub_category',
                  ]

    def __init__(self, *args, **kwargs):
        super(PortfolioForm, self).__init__(*args, **kwargs)
        self.fields['prefix'].widget.attrs['class'] = \
            "form-control"
        self.fields['experience'].widget.attrs['class'] = \
            "form-control"
        self.fields['budget'].widget.attrs['class'] = \
            "form-control"

ClientDashboard/templates/client_dashboard.html
CLIENT DASHBOARD



<a href="accounts/logout">
    <div class="menu-icon"><i class=" fa fa-sign-out"></i></div>
    <div class="menu-text">Logout</div>
</a>

<a href="{% url 'profile' %}">
    <div class="menu-icon"><i class=" fa fa-sign-out"></i></div>
    <div class="menu-text">Update profile</div>
</a>

ClientDashboard/templates/logout.html
LOGGED OUT

<a href="/client_login">LOGIN</a>

ClientDashboard/templates/profileSeting.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=1600, initial-scale=1, maximum-scale=1">
      <title>Iungo Advanced Technologies</title>
      <!-- styles -->
      <link rel="stylesheet" href="/static/font-awesome/css/font-awesome.min.css">
      <link rel="stylesheet" href="/static/css/main.css">
      <!-- javascripts -->
      <script src="/static/js/jquery-1.11.1.min.js"></script>
   </head>
   <body>
      <header>
         <div class="logo">
            <img src="/static/img/logo.png" alt="logo">
         </div>
      </header>
      <nav class="carousel">
         <div class="userProfile">
            <div id="user">
               <div class="imgtag">
                  {% if user.portfolio.profile_pic %}
                     <img src="/media/{{user.portfolio.profile_pic}}" alt="user">
                  {% else %}
                     <img src="/static/img/empty.png" alt="user">
                  {% endif %}
               </div>
               <div class="name">
                  <p>{{user.first_name}} {{user.last_name}}</p>
               </div>
            </div>
         </div>
         <div class="navItems">
            <div class="menuBtns">
               <ul>
                  <!-- <li><a  id="setting" href="#">Settings &nbsp; <i class="fa fa-cog" aria-hidden="true"></i></a></li> -->
                  <li><a href="/client/logout">Logout &nbsp; <i class="fa fa-power-off" aria-hidden="true"></i></a></li>
               </ul>
            </div>
         </div>
      </nav>
      <nav class="vertical-menu">
         <div id="sidebar-wrapper">
           <!-- <div id="btn-triangle-left"></div> -->
            <ul id="sidebar-nav">
               <li>
                  <a href="/client/overview">
                  <span class="imgs"><img src="/static/img/overview.svg" alt=""></span>
                  <span class="btnText">Overview</span>
                  </a>
               </li>

               <li>
                  <a class="active" href="/client/portfolio">
                  <span class="imgs"><img src="/static/img/profilesettings.svg" alt=""></span>
                  <span class="btnText">Profile Settings</span>
                  </a>
               </li>

               <!-- <li>
                  <a href="#">
                  <span class="imgs"><img src="/static/img/appointments.svg" alt=""></span>
                  <span class="btnText">Appointments</span>
                  </a>
               </li>
               <li>
                  <a class="arrowBtn" href="#">
                  <span class="imgs"><img src="/static/img/iungocloud.svg" alt=""></span>
                  <span class="btnText">Iungo Cloud</span>
                  </a>
               </li>
               <li>
                  <a href="#">
                  <span class="imgs"><img src="/static/img/feedbacks.svg" alt=""></span>
                  <span class="btnText">Feedbacks</span>
                  </a>
               </li>
               <li>
                  <a href="#">
                  <span class="imgs"><img src="/static/img/notification.svg" alt=""></span>
                  <span class="btnText">Notification</span>
                  </a>
               </li>
               <li>
                  <a href="#">
                  <span class="imgs"><img src="/static/img/reports.svg" alt=""></span>
                  <span class="btnText">Reports</span>
                  </a>
               </li> -->
            </ul>
         </div>
      </nav>
      <aside class="mainSection">
         <form class="mainForm" action="/client/portfolio/" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mrSelector">
               <label for="">Prefix<sup>*</sup></label><br>
               {{form.prefix}}
               {{form.prefix.errors}}
            </div>
            {% if user.first_name %}
               <div class="mrName">
                  <label for="userName">Name<sup>*</sup></label>
                  <input id="userName" type="text" name="userName" value="{{user.first_name}} {{user.last_name}}" disabled >
<!--                  <h6>Name cannot be changed after submitting once. Name, phone number, email id are the things needs permission to be changed.</h6>-->
               </div>
            {% else %}
               <div class="mrName">
                  <label for="userName">Name<sup>*</sup></label>
                  <input id="userName" type="text" name="userName" required >
<!--                  <p>Name cannot be changed after submitting once. Name, phone number, email id are the things needs permission to be changed.</p>-->
               </div>
            {% endif %}
            <br style="clear: both;">
               <div class="Gender">
               <label for="id_gender">Gender<sup>*</sup></label><br>
                  {{form.gender}}
                  {{form.gender.errors}}
               </div>
            <div class="emailIDForm">
               <label for="emailID">Email-id<sup>*</sup></label><br>
               <input id="emailID" type="email" name="emailID" placeholder="email Id"  value="{{user.email}}" disabled>
             </div>
            <br style="clear: both;">
            <div class="phone1">
              <label for="phoneNum1">Primary Number<sup>*</sup></label><br>
              <input id="phoneNum1" type="tel" name="phoneNum1" placeholder="+91"  value="{{user.portfolio.mobile_phone}}" disabled>
            </div>
            <div class="phone2">
              <label for="id_secondary_phone">Secondary Number<sup>*</sup></label><br>
               {{form.secondary_phone}}
               {{form.secondary_phone.errors}}
            </div>
            <br style="clear: both;">
            <div class="textareas">
               <p class="label">About Me/ Description</p>
               {{form.about_me}}
               {{form.about_me.errors}}
               <p style="float: right; font-size: 18px; margin-right: 238px;">250 characters long</p>
            </div>
            <div class="qualifications">
               <label for="QualificationsID">Qualifications<sup>*</sup></label><br>
               <div class="mrSelector qualifiSector ">
                  {{form.qualification}}
                  {{form.qualification.errors}}
               </div>
            </div>
            <div class="yearsofexperience">
                <label for="certificationsID">Years Of Experience<sup>*</sup></label><br>
               <div class="mrSelector qualifiSector ">
                  {{form.experience}}
                  {{form.experience.errors}}
               </div>
            </div>
            <br style="clear: both;">
            <div class="budget">
               <label for="budgetId">Budget<sup>*</sup></label><br>
               <div class="mrSelector qualifiSector ">
                  {{form.budget}}
                  {{form.budget.errors}}
               </div>
            </div>
            <div class="uploadProfilePicture">
              <label for="id_profile_pic">Profile Picture<sup>*</sup></label><br>
               <div class="mrSelector qualifiSector ">
                  {{form.profile_pic}}
                  {{form.profile_pic.errors}}
               </div>
            </div>
            <br style="clear: both;">
            <div class="category">
               <label for="categoryID">Category<sup>*</sup></label><br>
               <div class="mrSelector qualifiSector ">
                  {{form.category}}
                  {{form.category.errors}}
               </div>
            </div>
            <br style="clear: both;">
            <div class="category">
                <label for="id_sub_category">Sub Category<sup>*</sup></label><br>
               <div class="mrSelector qualifiSector ">
                  {{form.sub_category}}
                  {{form.sub_category.errors}}
               </div>
            </div>

            <br style="clear: both;">
            <div class="submitBtn">
               <div class="restBtn">
                  <input class="design_btn" type="submit" value="Submit"/>
                  <a href="/client/design_upload">
                  <input class="design_btn" type="button" value="Upload Designs and Projects"/>
                  </a>
               </div>


            </div>
         </form>
      </aside>
      <script src="/static/js/main.js"></script>

      <script type="text/javascript">

             $("#id_category").change(function () {
               var categoryId = $(this).val();
               console.log(categoryId)
               $.ajax({
                 url: '{% url 'load_sub_category' %}',
                 data: {
                   'category': categoryId
                 },
                 success: function (data) {
                   $("#id_sub_category").html(data);
                 }
               });

          });

       </script>




   </body>
</html>

ClientDashboard/templates/sub_categories.html
<option value="">---------</option>
{% for category in  sub_categories %}
<option value="{{ category.id }}">{{ category.name }}</option>
{% endfor %}

ClientDashboard/templates/upload_form.html
{% if type == 1%}

        <form class="mainForm" action="/client/design_upload/" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <br style="clear: both;">
            <div class="designType">
               <p class="label">Type<sup>*</sup> </p>
               <div class="mrSelector qualifiSector ">
                  {{form.design_type}}
                   {{form.design_type.errors}}
               </div>
            </div>
            <br style="clear: both;">
            <div class="designUploadNameID">
               <label for="id_design_name">Name<sup>*</sup></label><br>
               {{form.design_name}}
               {{form.design_name.errors}}
            </div>
            <br style="clear: both;">
            <div class="uploadFormimageUpload">
               <p class="label">Project Images<sup>*</sup> </p>
               {{form.design_images}}
               {{form.design_images.errors}}
            </div>
            <div class="submitBtn">
                   <input type="submit" value="Save"/>
            </div>
         </form>
         <div>
         <h5 class="YoursTitle">Your Design's</h5>
        {% if total_user_designs %}
            <div class="yourDesigns">
            {% for designs in total_user_designs %}
                <a href="{% url 'upload_details' %}?number={{designs.0.design_number}}&type=1">{{designs.0.design_name}} {{designs.0.design_type.name}}</a>
            {% endfor %}

           </div>
        {% endif %}
         </div>
{% elif type == 2%}
        <form class="mainForm" action="/client/project_upload/" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <br style="clear: both;">
            <div class="designType">
               <p class="label">Type<sup>*</sup> </p>
               <div class="mrSelector qualifiSector ">
                  {{form.project_type}}
                  {{form.project_type.errors}}
               </div>
            </div>
            <br style="clear: both;">
            <div class="designUploadNameID">
               <label for="id_project_name">Name<sup>*</sup></label><br>
               {{form.project_name}}
               {{form.project_name.errors}}
            </div>
            <br style="clear: both;">
            <div class="uploadFormimageUpload">
               <p class="label">Project Images<sup>*</sup> </p>
               {{form.project_images}}
               {{form.project_images.errors}}
            </div>
            <div class="submitBtn">
                   <input type="submit" value="Save"/>

            </div>
         </form>
        <div>
            <h5 class="YoursTitle">Your Project's</h5>
        {% if total_user_projects %}
            <div class="yourDesigns">
            {% for projects in total_user_projects %}
                <a href="{% url 'upload_details' %}?number={{projects.0.project_number}}&type=2">{{projects.0.project_name}}-{{projects.0.project_type.name}}</a>
            {% endfor %}
            </div>
        {% endif %}
        </div>
{% endif %}

ClientDashboard/templates/welcome.html
WELCOME